// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFA_omeBGwuLb3RdzAOkAGWH8i4eOMruk',
    appId: '1:889471056206:web:00b2eb661a399621ec461f',
    messagingSenderId: '889471056206',
    projectId: 'evolve-6a292',
    authDomain: 'evolve-6a292.firebaseapp.com',
    databaseURL: 'https://evolve-6a292-default-rtdb.firebaseio.com',
    storageBucket: 'evolve-6a292.appspot.com',
    measurementId: 'G-PGR1F1397Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3SMiu_CaERllktjKyTIuBz2ZJXNEQlZs',
    appId: '1:889471056206:android:804e862797cf6b03ec461f',
    messagingSenderId: '889471056206',
    projectId: 'evolve-6a292',
    databaseURL: 'https://evolve-6a292-default-rtdb.firebaseio.com',
    storageBucket: 'evolve-6a292.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvDEs-ppvij9BlvLMDQsnja4J8l27BOw',
    appId: '1:889471056206:ios:fe09486af8695db7ec461f',
    messagingSenderId: '889471056206',
    projectId: 'evolve-6a292',
    databaseURL: 'https://evolve-6a292-default-rtdb.firebaseio.com',
    storageBucket: 'evolve-6a292.appspot.com',
    iosBundleId: 'com.example.evolve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkvDEs-ppvij9BlvLMDQsnja4J8l27BOw',
    appId: '1:889471056206:ios:fe09486af8695db7ec461f',
    messagingSenderId: '889471056206',
    projectId: 'evolve-6a292',
    databaseURL: 'https://evolve-6a292-default-rtdb.firebaseio.com',
    storageBucket: 'evolve-6a292.appspot.com',
    iosBundleId: 'com.example.evolve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFA_omeBGwuLb3RdzAOkAGWH8i4eOMruk',
    appId: '1:889471056206:web:18447fe2c37809b6ec461f',
    messagingSenderId: '889471056206',
    projectId: 'evolve-6a292',
    authDomain: 'evolve-6a292.firebaseapp.com',
    databaseURL: 'https://evolve-6a292-default-rtdb.firebaseio.com',
    storageBucket: 'evolve-6a292.appspot.com',
    measurementId: 'G-S133TJ1G2D',
  );
}
